#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "suhassan/11213803@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
CREATE TABLE ACCOUNT 
(
USERNAME VARCHAR2(25 BYTE) 
, ID NUMBER(*, 0) NOT NULL 
, PASSWORD VARCHAR2(12 BYTE) 
, EMAIL VARCHAR2(20 BYTE) 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT ACCOUNT_PK PRIMARY KEY 
(
ID 
)
USING INDEX 
(
CREATE INDEX USERS_PK ON ACCOUNT (ID ASC) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
)
ENABLE 
) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
CREATE TABLE PAYMENT 
(
CONFIRMATION_NUM NUMBER(*, 0) NOT NULL 
, PRICE BINARY_DOUBLE 
, DISCOUNT BINARY_DOUBLE 
, TYPE VARCHAR2(20 BYTE) 
, BILLING_ADDRESS VARCHAR2(20 BYTE) 
, DATES DATE 
, CONSTRAINT PAYMENT_PK PRIMARY KEY 
(
CONFIRMATION_NUM 
)
USING INDEX 
(
CREATE INDEX PAYMENT_PK ON PAYMENT (CONFIRMATION_NUM ASC) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
)
ENABLE 
) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
CREATE TABLE REVIEWS 
(
SELLER VARCHAR2(20 BYTE) NOT NULL 
, RATING NUMBER(*, 0) 
, SERVICES VARCHAR2(20 BYTE) 
, DATES DATE 
, SERVICE_TYPE VARCHAR2(20 BYTE) 
, CONSTRAINT REVIEWS_PK PRIMARY KEY 
(
SELLER 
)
USING INDEX 
(
CREATE INDEX REVIEWS_PK ON REVIEWS (SELLER ASC) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
)
ENABLE 
) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
CREATE TABLE SELLER 
(
INBOX_RESPONSE VARCHAR2(30 BYTE) 
, EARNINGS VARCHAR2(20 BYTE) 
, ORDER_COMPLETION_RATE VARCHAR2(20 BYTE) 
, DELIEVERD_ON_TIME_RATE VARCHAR2(20 BYTE) 
, ORDER_RESPONSE_RATE VARCHAR2(20 BYTE) 
, ID NUMBER(*, 0) NOT NULL 
, CONSTRAINT SELLER_PK PRIMARY KEY 
(
ID 
)
USING INDEX 
(
CREATE INDEX SELLER_PK ON SELLER (ID ASC) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
)
ENABLE 
) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
CREATE TABLE SERVICE 
(
ID NUMBER(*, 0) NOT NULL 
, DESCRIPTION VARCHAR2(100 BYTE) 
, PORTFOLIO VARCHAR2(20 BYTE) 
, NAME VARCHAR2(20 BYTE) 
, LEVELS VARCHAR2(20 BYTE) 
, SERVICE_NAME VARCHAR2(20 BYTE) 
, SERVICE_TYPE VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
CREATE INDEX SERVICE_PK ON SERVICE (ID ASC) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
ALTER TABLE SERVICE
ADD CONSTRAINT SERVICE_PK PRIMARY KEY 
(
ID 
)
USING INDEX SUHASSAN.SERVICE_PK
ENABLE;
CREATE TABLE SERVICELEVEL 
(
ID NUMBER(*, 0) NOT NULL 
, TYPE VARCHAR2(20 BYTE) 
, PRICE VARCHAR2(20 BYTE) 
, DESCRIPTION VARCHAR2(500 BYTE) 
, RESPONSE_TIME_MINS NUMBER 
, DELIVERY_TIME_DAYS NUMBER 
) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
CREATE INDEX SERVICELEVEL_PK ON SERVICELEVEL (ID ASC) 
LOGGING 
TABLESPACE DBCOURSE 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
INITIAL 65536 
NEXT 1048576 
MINEXTENTS 1 
MAXEXTENTS UNLIMITED 
BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
ALTER TABLE SERVICELEVEL
ADD CONSTRAINT SERVICELEVEL_PK PRIMARY KEY 
(
ID 
)
USING INDEX SUHASSAN.SERVICELEVEL_PK
ENABLE;
EXIT;
EOF
